### PR TITLE
Remove Reps app.

### PR DESCRIPTION
**Pull request by akatsoulas**
Reps site has been decommissioned and the domain is redirecting to the community portal. The existing url triggers a 404.

### CODE REVIEW

**Comment by gene1wood** [comment]
Along with this you'll need to delete the client https://manage.mozilla.auth0.com/dashboard/pi/auth/applications/zwpij4T2QTt7QdbmdpkAG5FQgoeSRbyB/settings

**Review by gene1wood — APPROVED** [review]

**Comment by gene1wood** [comment]
@akatsoulas can you add to this PR the deletion of https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/images/reps.png

**Comment by akatsoulas** [comment]
@gene1wood PR updated. Regarding the client, I don't have access to Auth0 for the deletion.

**Comment by gene1wood** [comment]
> Regarding the client, I don't have access to Auth0 for the deletion.

Totally, just a reminder for the IAM team when they process this PR.

Thank you for it!

**Review by gene1wood — APPROVED** [review]

**Comment by sciurus** [comment]
I've deleted the client.

**Review by floatingatoll — APPROVED** [review]
+1 (cc @pwnbus, in case you end up doing a deploy sometime)

**Comment by gene1wood** [comment]
Closing this in favor of #478 which has a signed commit (which is required for this repo)

**Pull request closed without merging**
