### PR TITLE
Create app for buzilla-dev.allizom.org

### PR DESCRIPTION
**Pull request by The-smooth-operator**
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1671709

### CODE REVIEW

**Review by gene1wood — COMMENTED** [review]
Is the `url` value in this PR correct?

https://github.com/mozilla-iam/sso-dashboard-configuration#fields-reference
```

      ### SSO Dashboard display settings
      # This is the URL that a user must visit to be logged into the RP. This URL would
      # either be the URL of the login button on the site (if it has one), or the URL
      # that a user gets redirected to when they visit a protected page while unauthenticated.
```

**Comment by The-smooth-operator** [comment]
> Is the `url` value in this PR correct?

Thanks for your review @gene1wood. 
I did take into account that the URL should be the target where a user can login in.
In this case, the login URL is the same as the main URL because when we click "Log in" we get prompted with an embedded form and not getting redirected to other login page.

image

It's also true that the app rewrites the URI to to `/home` but since there aren't any redirects (no more hops) I thought this will be more stable.

**Review by limed — APPROVED** [review]
r+ there is a conflict so you have to resolve that first

**Comment by The-smooth-operator** [comment]
Once the integration is setup, and if we want to display the URL in the dashboard for prod we will pick the URL which brings the user to the site authenticated

**Pull request merged**
