### PR TITLE
Remove chronicle app

### PR DESCRIPTION
**Pull request by pwnbus**

### CODE REVIEW

**Review by floatingatoll — APPROVED** [review]
This URL still resolves, but it redirects to Auth0, which then servfail's due (presumably) to the integration having been removed from Auth0. Tentative r+.

**Comment by gene1wood** [comment]
Make sure to also remove the `ICT9TtChxTlLMrHlLjeMeLH0x6vG31Ai` client from Auth0 management UI

**Review by dividehex — APPROVED** [review]
Looks like `ICT9TtChxTlLMrHlLjeMeLH0x6vG31Ai` has been removed from Auth0 prod.  @pwnbus  would you like me to merge and deploy this?

**Comment by pwnbus** [comment]
@dividehex Feel free to merge and deploy at your leisure, no rush from my side.

**Pull request merged**
