### PR TITLE
mentoring app is on dotcom not dotorg

### PR DESCRIPTION
**Pull request by sciurus**
https://jira.mozilla.com/browse/SE-1483

### CODE REVIEW

**Review by gene1wood — APPROVED** [review]

**Review by duallain — APPROVED** [review]
LGTM.  One note @sciurus we may need to update the auth0 client to allow .com access, it seems like maybe the callback url isn't currently allowed.

**Comment by gene1wood** [comment]
> we may need to update the auth0 client to allow .com access, it seems like maybe the callback url isn't currently allowed.

Good point, if the URL of the allowed callbacks is also wrong in Auth0 it will need to be updated.

**Comment by sciurus** [comment]
@gene1wood @duallain when I check allowed callback URLs in Auth0 I see "https://mentoring.mozilla.com/oidc/callback/" which looks right.

**Comment by sciurus** [comment]
Force-pushing a signed version of the commit

**Pull request merged**
