### PR TITLE
Expand AWS SSO access to non staff in mozillians group searchfox-aws

### PR DESCRIPTION
**Pull request by gene1wood**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1677158

### CODE REVIEW

**Comment by staktrace** [comment]
@sidler-mozilla ping, do you have an ETA on this? (this is blocking some work I'd like to do on searchfox). Thanks!

**Review by The-smooth-operator — APPROVED** [review]

**Comment by staktrace** [comment]
Thanks! Do you know if this gets deployed automatically, or is it periodic? (Thus far I still cannot log in to AWS via SSO)

**Comment by The-smooth-operator** [comment]
@staktrace the deployment is manually triggered. It should be deployed now. Can you check it again?

**Comment by staktrace** [comment]
@The-smooth-operator yes it works now, thank you!

**Pull request merged**
