### PR TITLE
Deployments to Google CDN

### PR DESCRIPTION
**Pull request by dividehex**
This PR sets Github Actions to deploy the SSO Dashboard configuration to a google cloud bucket in anticipation of migrating out of AWS.  It does not affect the existing AWS code build deployment that deploys the configuration.

### CODE REVIEW

**Review by floatingatoll — APPROVED** [review]
These seem general reasonable and I'm glad to see the version increments on existing automation. I can't offer any GCP-specific advice, but so long as this lands cleanly and you're still able to merge and deploy PRs, wfm.

**Review by gcoxmoz — COMMENTED** [review]
Belated, but, I have no review of any value to add here, sorry.

**Comment by bkochendorfer** [comment]
Awesome, are you all using the standard GCP deployment framework? I don't see a sso-dashboard app listed

**Comment by floatingatoll** [comment]
(Redirecting that question to Slack.)

**Pull request merged**
