### PR TITLE
Add configuration for Netlify

### LINKED ISSUE #293: Add Netlify

### PR DESCRIPTION
**Pull request by gozer**
Fixes #293

### CODE REVIEW

**Comment by jdow** [comment]
I can't merge this because the commit isn't signed/verified.

**Comment by gozer** [comment]
This is a really really annoying github bug with my GPG key, unfortunately. My commits *are* GPG signed, github just doesn't handle my key proprely...

**Comment by jdow** [comment]
@andrewkrug not sure what to do with this, since merging is blocked because github can't verify gozer's key. Any ideas?

**Comment by gdestuynder** [comment]
@jdow  reauthor the commit, or the setup from @gozer would have to be fixed by/with GitHub 
If there is something that isn't going to be fixed (do you know of an issue at GitHub for this?) I'd recommend reauthoring always or creating a github-specific key

**Comment by gdestuynder** [comment]
and with that https://github.com/mozilla-iam/sso-dashboard-configuration/pull/298

**Pull request closed without merging**
