### PR TITLE
Add valimail [IAM-920]

### PR DESCRIPTION
**Pull request by floatingatoll**
This is a re-submit of #548 with the client_id corrected.

### CODE REVIEW

**Comment by floatingatoll** [comment]
(We should hold on merging this until the correct set of users are in the mozilliansorg group.)

**Comment by dividehex** [comment]
There is already an entry for client id `wXpnkKIgoucVrybZmxiPnnpeSqn816qD` at line 3750.  That should probably be remove in favor of adding this.

**Comment by floatingatoll** [comment]
Agreed, good catch.

**Comment by floatingatoll** [comment]
Updated to reflect that.

**Review by dividehex — APPROVED** [review]
r+ lgtm

**Pull request merged**
