### PR TITLE
Do not merge until Oct 1st: Open up Tripactions and close down Egenica

### PR DESCRIPTION
**Pull request by sciurus**
This opens tripactions to moco/mofo/pocket and locsk egencia down to
the travel team.

https://bugzilla.mozilla.org/show_bug.cgi?id=1707014

### CODE REVIEW

**Review by smarnach — COMMENTED** [review]
Is this intended as a hard cut-over, with people losing access to Egencia at the same time they gain access to Tripactions? What happens to trips that are already booked via Egencia, but are still in the future at the time of the cutover?

**Comment by sciurus** [comment]
Hi Sven, thanks for the questions, but no need for you to review SSO dashboard PRs!

Yes, what you described is the plan that Jen and the travel team have made. Details are in the bugzilla link.

**Review by dividehex — APPROVED** [review]
👍 LGTM.  I'll handle the merging and release on 7/30.

**Comment by dividehex** [comment]
@websre-west I'd like to get another review on this since I've added changes to the PR

**Comment by floatingatoll** [comment]
I tried looking at this to review it, but I just don't have enough context
to know whether my questions are valid or not. It seems like valid YAML.

**Pull request merged**
