### PR TITLE
Grant MozillaOnline employees access to telemetry services (cont'd)

### PR DESCRIPTION
**Pull request by l-hedgehog**
As a followup to #435, which doesn't include the other three telemetry related services as confirmed by @jasonthomas in https://bugzil.la/1693956#c4 .

I'm not sure which one of "GLAM" or "GLAM (prod)" is the right one, so updated them both.

r?@The-smooth-operator

Thanks!

### CODE REVIEW

**Comment by sciurus** [comment]
@l-hedgehog the-smooth-operator is out on leave.

LTGM. @duallain can you provide a second set of eyes?

**Review by duallain — APPROVED** [review]
LGTM.   Based on the previous conversation we OK'd this access, so it makes sense to show the tiles on the dashboard.

**Comment by sciurus** [comment]
@l-hedgehog can you sign this commit?

https://docs.github.com/articles/about-gpg/

**Comment by l-hedgehog** [comment]
> @l-hedgehog can you sign this commit?

Hi @sciurus I pushed a signed commit.

**Pull request merged**
