### PR TITLE
Adding tile for marketing's email service Everest

### PR DESCRIPTION
**Pull request by duallain**
Service provided by validity.
Related to the setup request from https://bugzilla.mozilla.org/show_bug.cgi?id=1686120

### CODE REVIEW

**Comment by duallain** [comment]
@gene1wood this is the first one of these I've done, so a bit more scrutiny is probably warranted, but I took a look at a few previous PRs and this seems to be good based on those.

**Review by gene1wood — COMMENTED** [review]
Alan, this looks correct. Group looks good. URL redirects to SSO login which is correct. It looks like the `everest.png` is an "empty file"? Is that expected? I'd assume it would have some size as it would be the tile image.

**Comment by duallain** [comment]
@gene1wood not sure honestly, I see what you're talking about with the file being listed as empty, but on both my machine and hitting it directly (like the below link) it seems to look alright.

(I just checked again and now it's showing binary file data not shown, which is the correct behavior.  Happened after in the pr/files view I selected the 'display rich preview' button and then back to 'display source diff')

https://github.com/mozilla-iam/sso-dashboard-configuration/blob/dd2432851c43b84cba663a5ea7af78998131903c/images/everest.png

**Review by gene1wood — APPROVED** [review]
Got it, ok just some weird GitHub UI issue.

**Pull request merged**
