### PR TITLE
Remove entries from apps.yml for items I know have been decom'ed

### PR DESCRIPTION
**Pull request by gcoxmoz**
These are former datacenter resources, all decom'ed.

### CODE REVIEW

**Review by bkochendorfer — APPROVED** [review]

**Comment by bkochendorfer** [comment]
@gcoxmoz looks like you have to sign this commit

**Comment by gene1wood** [comment]
Here are all the client_ids which exist in `apps.yml` but which don't exist in production Auth0

```
RqUns8zD5oTsEsjTKAUMhF55sLfuQsGv
3LIXec4tKVr6SltYFYUYsE0GIw0Jm2T0
GmGXMS6RJt3ZvabfTjx16B97pETlnUxd
kNsY9QiOy7pSUjiordq7WixztBPCepuD
nPr8QRo0dLxM3RRHwIXRSvhmOSPDvNr4
a145ph7ZPSz97z8QkiuP1iId6MFPXXUH
BRMXeyw2avAOj7GgBD4SuIHxopb0yZJP
FeqjZfpOqMIkcGKkd2fDjpnm5oSsOOZ2
mc1l0G4sJI2eQfdWxqgVNcRAD9EAgHib
HvN5D3R64YNNhvcHKuMKny1O0KJZOOwH
WLQrmFTcXlSDelnxOASZ4KJQTE5gXZFt
M4TY5gZQ6nUyMIjWpXWFffRJ9pD3qPb2
y2cZ14lTdsMjJdjmUNQ3PaLDrBCNJUZl
M6lxk8phwDaqH4gECMWDLxKxxZwJcDI7
```

and here are the client_ids in apps.yml which don't exist in prod or dev. These should be removed from apps.yml

```
M6lxk8phwDaqH4gECMWDLxKxxZwJcDI7
BRMXeyw2avAOj7GgBD4SuIHxopb0yZJP
FeqjZfpOqMIkcGKkd2fDjpnm5oSsOOZ2
RqUns8zD5oTsEsjTKAUMhF55sLfuQsGv
WLQrmFTcXlSDelnxOASZ4KJQTE5gXZFt
HvN5D3R64YNNhvcHKuMKny1O0KJZOOwH
3LIXec4tKVr6SltYFYUYsE0GIw0Jm2T0
mc1l0G4sJI2eQfdWxqgVNcRAD9EAgHib
```

**Comment by floatingatoll** [comment]
Websre, we need to verify that the apps are torn down in Auth0 before merging patches to remove them from apps.yml, or else we can end up in weird scenarios with the SSO system.

**Comment by gene1wood** [comment]
> Do you have scripts/tooling that you're using to get this information from Auth0 so easily?

I queried the management API to get a list of client_ids (in dev and prod Auth0 tenants ) : https://auth0.com/docs/api/management/v2/#!/Clients/get_clients
Then parsed the `apps.yml` to extract all the client_ids from that.
Then did a python set subtraction to see what was present in `apps.yml` but missing from prod and dev auth0

**Comment by floatingatoll** [comment]
Queried using what methods, scripts, and/or from-memory code? Are you writing bare API clients from scratch every time to do this, using the Python debugger CLI? Did you extract client ids both from the client_id field and from the .com/samlp URLs that contain client IDs?

While I do appreciate the written breakdown of how you did it, it doesn't provide me much information that I didn't already have. If you have convenience artifacts leftover from your IAM work that we would benefit from, please do reconsider whether you're willing to let us see them or not. They don't need to be tidy, neat, or public, but we're in a desert and you seem able to conjure water out of thin air, so anything will surely help.

**Comment by gene1wood** [comment]
> Queried using what methods, scripts, and/or from-memory code

I was just doing an interactive python session. I also have a little bash helper script I use to talk to the management API

```shell
export client_id=
export client_secret=
export audience=auth.mozilla.auth0.com

if [ -z "$management_api_bearer_token" ]; then
    echo "Fetching bearer token"
    export management_api_bearer_token=$(curl --silent --request POST --url \
       https://${audience}/oauth/token \
       --header "Content-Type: application/json" --data "{\"client_id\":\"${client_id}\",\"client_secret\":\"${client_secret}\",\"audience\":\"https://${audience}/api/v2/\",\"grant_type\":\"client_credentials\"}" | jq -r '.access_token')
fi


function get_applications {
    curl --silent -H "Authorization: Bearer ${management_api_bearer_token}" "https://${audience}/api/v2/clients?fields=client_id,name" \
      | jq 'sort_by(.name)' | jq -r '.[] | {name: .name, client_id: .client_id} | @text'
} 
```

> Are you writing bare API clients from scratch every time to do this, using the Python debugger CLI?

Ya, pretty much. Though this kind of check (comparing `apps.yml` to the contents of Auth0 via the management API would be trivial to setup as a nightly lambda job or something)

> Did you extract client ids both from the client_id field and from the .com/samlp URLs that contain client IDs?

No, I only used the `client_id` field in the yaml.

> please do reconsider whether you're willing to let us see them or not

Of course, you're welcome to anything I have.

> They don't need to be tidy, neat, or public, but we're in a desert and you seem able to conjure water out of thin air, so anything will surely help.

Ya in this case, I just thought "oh hey, I can pull all the client_ids from the `apps.yml` because it's yaml. And I can query the management API for client_ids. And then I could compare them to see how they differ"

**Pull request closed without merging**
