### PR TITLE
Reflect New Relic RPs.

### PR DESCRIPTION
**Pull request by The-smooth-operator**
The reason why not displaying the icon is because AFAIK the members of each NR account are not matching with any pre-existent group

### CODE REVIEW

**Comment by jdow** [comment]
These entries don't have a client_id which is what is used for access control. Without a client ID, an entry is only useful for dashboard display, but since that is false, I think this is not needed.

**Comment by The-smooth-operator** [comment]
@jdow should I add the client_id field for each entry?

**Comment by jdow** [comment]
Yes, which should be the string in the URL. For  https://auth.mozilla.auth0.com/samlp/Um2rLocE3s851JXNZzTPnA5DFzWe9OhQ , the client ID is Um2rLocE3s851JXNZzTPnA5DFzWe9OhQ

**Comment by The-smooth-operator** [comment]
thanks, I've updates the PR.

**Comment by gdestuynder** [comment]
@jdow

**Pull request merged**
