### PR TITLE
add balrog

### PR DESCRIPTION
**Pull request by gdestuynder**
@mozbhearsum  (production deploy triggers from this)

### CODE REVIEW

**Comment by gdestuynder** [comment]
@jdow

**Comment by mozbhearsum** [comment]
Thanks! Should Balrog show up on https://sso.mozilla.com/dashboard now?

**Comment by gdestuynder** [comment]
yes, granted that are in the groups

**Comment by mozbhearsum** [comment]
Hmm, it's not showing up for me:
image

@jdow - do you have any idea why?

**Comment by jdow** [comment]
I don't see a reason why it wouldn't show up. @andrewkrug can you check if this deployed properly?

**Comment by gdestuynder** [comment]
https://jira.mozilla.com/projects/EIS/issues/EIS-780

@mozbhearsum this should be fixed now and theres additional info on that link
There's also a new external check to ensure the update propagate properly

Thanks!

**Comment by mozbhearsum** [comment]
I see it - thanks!

**Pull request merged**
