### PR TITLE
Grant MozillaOnline employees access to telemetry services

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
Requested in Bugzilla bug 1693956

**Review by gene1wood — CHANGES_REQUESTED** [review]
Make sure not to merge and deploy this until someone in telemetry authorizes the request for access from mozillaonline

**Comment by sciurus** [comment]
Jason THomas has authorized this at https://bugzilla.mozilla.org/show_bug.cgi?id=1693956#c4

**Review by sciurus — APPROVED** [review]

**Comment by l-hedgehog** [comment]
Hi @The-smooth-operator , can you please also add us to the other three services including GLAM, which :jthomas confirmed in his comment are also relevant. Thanks!

**Pull request merged**
