### PR TITLE
Remove non-existent Heroku apps

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
Reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1691630

**Comment by The-smooth-operator** [comment]
After merging and deploying it, I'll be cleaning up the references in Auth0.

**Review by limed — APPROVED** [review]
r+

**Comment by gene1wood** [comment]
@The-smooth-operator Make sure to also delete the clients from Auth0 once you remove them from `apps.yml`

**Comment by The-smooth-operator** [comment]
@gene1wood sure, it is part of my list when I remove an application from here.

**Comment by The-smooth-operator** [comment]
Apps have been deleted from Auth0 now.

**Pull request merged**
