### PR TITLE
Allow zoomadmin to access jira, bug 1795163

### PR DESCRIPTION
**Pull request by gcoxmoz**
https://bugzilla.mozilla.org/show_bug.cgi?id=1795163

### CODE REVIEW

**Review by floatingatoll — COMMENTED** [review]
I've raised two concerns in the bug for consideration, but this PR is structurally sound and would have the desired effect.

**Review by VegasNative — APPROVED** [review]
based on the last comment in the bug, marking this as approved.

**Review by VegasNative — APPROVED** [review]
sorry... forgot to hit the checkmark. approving attempt #2 :)

**Review by ctbfourone — APPROVED** [review]
+1

**Pull request merged**
