### PR TITLE
added Pigment app to apps.yml

### PR DESCRIPTION
**Pull request by vansterzzz**
iam-1223, added pigment app.

### CODE REVIEW

**Review by ctbfourone — APPROVED** [review]
+1, looks good, but to confirm: you don't want this to be visible?

**Comment by vansterzzz** [comment]
@ctbfourone, i'm waiting for them to send me a tile then i'll create another PR. is that how i should be handling these requests?

**Comment by ctbfourone** [comment]
Yeah, that's fine, but if you get it soonish then you can just add that as another commit to this branch and then it can all get merged all at once. But if they need login ability more importantly than the dashboard tile then doing it in two PRs is totally legit. Up to you.

**Comment by vansterzzz** [comment]
@ctbfourone/ @dividehex  i've received and committed the pigment tile. please review and merge/deploy at your convenience.

**Review by ctbfourone — APPROVED** [review]
Looks good!

**Pull request merged**
