### PR TITLE
Create TripActions application

### PR DESCRIPTION
**Pull request by The-smooth-operator**
This PR will enable SSO for TripActions application. See [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1672012) for more info

### CODE REVIEW

**Review by limed — APPROVED** [review]
r+

**Review by gene1wood — CHANGES_REQUESTED** [review]
Alberto, much better than granting individual users access to an RP is to identify a curator who can curate an access group membership, and add that access group. That way in the future if there are changes to membership, it need not require you to make code changes in this repo, and the group curator can instead just add or remove users from the group. Users can create access groups here https://people.mozilla.org/a/ and if they do you can then add them to the `authorized_groups` field.

For example if the curator creates group `foo` then you'd add `mozilliansorg_foo` to the `authorized_groups`

**Comment by The-smooth-operator** [comment]
Gene, this makes complete sense. I've added a new group and pushed (squashed) the changes

**Review by gene1wood — APPROVED** [review]

**Comment by gene1wood** [comment]
Also it looks like the URL is actually `https://auth.mozilla.auth0.com/samlp/i1qBrMjJEdKlTNEVgGwc9P0xFxI9cuD8`. I'll put in a PR to fix that.

**Pull request merged**
